import type {TuiColor} from '../../utils/color';
import type {TuiSizeValue, TuiBorderStyleName} from '../types';

export type TextareaWidgetOptions = {
  x?: TuiSizeValue;
  y?: TuiSizeValue;
  width?: TuiSizeValue;
  height?: TuiSizeValue;
  colorFg?: TuiColor;
  colorBg?: TuiColor;
  colorFgNormal?: TuiColor;
  colorBgNormal?: TuiColor;
  colorFgFocused?: TuiColor;
  colorBgFocused?: TuiColor;
  placeholder?: string;
  colorPlaceholder?: TuiColor;
  value?: string;
  colorBorderUnfocused?: TuiColor;
  colorBorderFocused?: TuiColor;
  colorBorderDisabled?: TuiColor;
  borderStyle?: TuiBorderStyleName;
  maxLength?: number;
  colorSelectionBg?: TuiColor;
  colorSelectionFg?: TuiColor;
  label?: string;
  readonly?: boolean;
  disabled?: boolean;
  colorFgDisabled?: TuiColor;
  colorBgDisabled?: TuiColor;
  colorScrollbar?: TuiColor;
  colorScrollbarTrack?: TuiColor;
};
