export const PROP_UPDATE_MAP: Record<string, {method: string; field: string}> = {
  x: {method: 'updateRect', field: 'x'},
  y: {method: 'updateRect', field: 'y'},
  width: {method: 'updateRect', field: 'width'},
  height: {method: 'updateRect', field: 'height'},
  colorFg: {method: 'updateColor', field: 'colorFg'},
  colorBg: {method: 'updateColor', field: 'colorBg'},
  zIndex: {method: 'updateStyle', field: 'styleZIndex'},
  styleModifier: {method: 'updateStyle', field: 'styleModifier'},
  border: {method: 'updateBorder', field: 'border'},
  borderColor: {method: 'updateBorder', field: 'borderColor'},
  borderStyle: {method: 'updateBorder', field: 'borderStyle'},
  borderTop: {method: 'updateBorder', field: 'borderTop'},
  borderRight: {method: 'updateBorder', field: 'borderRight'},
  borderBottom: {method: 'updateBorder', field: 'borderBottom'},
  borderLeft: {method: 'updateBorder', field: 'borderLeft'},
  shadowOffsetX: {method: 'updateShadow', field: 'shadowOffsetX'},
  shadowOffsetY: {method: 'updateShadow', field: 'shadowOffsetY'},
  shadowColor: {method: 'updateShadow', field: 'shadowColor'},
  shadowCovered: {method: 'updateShadow', field: 'shadowCovered'},
  value: {method: 'updateValue', field: ''},
  direction: {method: 'updateDirection', field: ''},
  gap: {method: 'updateGap', field: ''},
  align: {method: 'updateAlign', field: ''},
  paddingTop: {method: 'updatePadding', field: 'paddingTop'},
  paddingBottom: {method: 'updatePadding', field: 'paddingBottom'},
  paddingLeft: {method: 'updatePadding', field: 'paddingLeft'},
  paddingRight: {method: 'updatePadding', field: 'paddingRight'},
};

export const FLAG_PROP_MAP: Record<string, string> = {
  draggable: 'setDraggable',
  disabled: 'setDisabled',
  checked: 'setChecked',
  indeterminate: 'setIndeterminate',
  readonly: 'setReadonly',
  label: 'setLabel',
  tabs: 'setOptions',
  options: 'setOptions',
  visible: 'setVisible',
};

export const BOOLEAN_FLAGS = new Set(['disabled', 'checked', 'readonly', 'draggable']);
